- hosts: app_servers
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull application image
      docker_container:
        name: jenkins-demo
        image: nihalpk/jenkins-demo:latest
        state: started
        recreate: yes
        ports:
          - "80:8080"
